
import { Scholarship, Provider, SuccessStory } from './types';

export const mockProviders: Provider[] = [
    {
        id: 'mbhte',
        slug: 'mbhte',
        name: 'Ministry of Basic, Higher and Technical Education (MBHTE)',
        logo: 'https://placehold.co/200x200?text=MBHTE',
        type: 'Government Agency',
        website: 'https://mbhte.bangsamoro.gov.ph',
        about: 'The Ministry of Basic, Higher and Technical Education is responsible for the formulation, planning, implementation, and coordination of policies, plans, programs and projects in the areas of basic, higher and technical education in the Bangsamoro Autonomous Region in Muslim Mindanao.',
        mission: 'To provide accessible, quality, and relevant education to the Bangsamoro people.',
        statistics: {
            activePrograms: 3,
            activeScholars: 1240,
            disbursedAmount: '₱45M+',
        },
        contact: {
            address: 'BARMM Government Center, Cotabato City',
            email: 'scholarships@mbhte.bangsamoro.gov.ph',
            phone: '(064) 123-4567',
        },
    },
    {
        id: 'most',
        slug: 'most',
        name: 'Ministry of Science and Technology (MOST)',
        logo: 'https://placehold.co/200x200?text=MOST',
        type: 'Government Agency',
        website: 'https://most.bangsamoro.gov.ph',
        about: 'The Ministry of Science and Technology is the primary agency in the region responsible for the development of science and technology programs and activities.',
        statistics: {
            activePrograms: 2,
            activeScholars: 850,
            disbursedAmount: '₱30M+',
        },
        contact: {
            address: 'BARMM Government Center, Cotabato City',
            email: 'info@most.bangsamoro.gov.ph',
            phone: '(064) 987-6543',
        },
    },
];

export const mockScholarships: Scholarship[] = [
    {
        id: 'ahme-2026',
        name: 'AHME Scholarship',
        provider: 'MBHTE',
        providerId: 'mbhte',
        amount: '₱80,000/year',
        deadline: 'March 15, 2026',
        level: 'College',
        status: 'Open',
        courses: ['STEM', 'Health Sciences', 'Education', 'Agriculture', 'Engineering', 'IT/Computer Science'],
        location: 'BARMM Residents',
        description: "The Access to Higher and Modern Education (AHME) program is MBHTE's flagship scholarship initiative designed to provide financial assistance to qualified Bangsamoro students pursuing higher education in priority courses aligned with BARMM's development agenda.",
        benefits: [
            'Tuition & Fees: Up to ₱40,000/semester',
            'Living Allowance: ₱5,000/month',
            'Book Allowance: ₱5,000/semester',
            'Thesis/Project Fund: ₱10,000 (final year)',
            'Mentorship Access: Paired with industry professional',
        ],
        eligibility: [
            'Must be a BARMM resident (with valid proof of residency)',
            'Filipino citizen',
            'Incoming freshman or continuing college student',
            'Minimum GWA of 85% or equivalent',
            'Combined annual family income below ₱400,000',
            'Not a recipient of other government scholarships',
            'Enrolled in an accredited HEI in a priority course',
        ],
        requirements: [
            'Completed Application Form',
            'Certificate of Residency (Barangay/Municipal)',
            'Birth Certificate (PSA copy)',
            'Transcript of Records / Form 137',
            'Certificate of Good Moral Character',
            '2x2 ID Photo (white background)',
            'Proof of Family Income (ITR/Certificate of Indigency)',
            'Recommendation Letter (Principal/Guidance Counselor)',
        ],
        slots: { total: 500, remaining: 250 },
        duration: '4 years (or until grad)',
        renewable: true,
    },
    {
        id: 'base-merit-2026',
        name: 'BASE-Merit Program',
        provider: 'MOST',
        providerId: 'most',
        amount: 'Full Scholarship',
        deadline: 'February 28, 2026',
        level: 'College',
        status: 'Closing',
        courses: ['Science', 'Technology', 'Engineering', 'Mathematics'],
        location: 'BARMM Residents',
        description: 'The Bangsamoro Assistance for Science Education (BASE)-Merit is for students with high aptitude in science and technology.',
        benefits: ['Full Tuition', 'Monthly Stipend', 'Learning Materials'],
        eligibility: ['Top 5% of graduating class', 'STEM Strand', 'BARMM Resident'],
        requirements: ['Form 138', 'Certificate of Residency', 'PSA Birth Certificate'],
    },
    {
        id: 'medical-allied-2026',
        name: 'Medical Allied Scholarship',
        provider: 'MOH',
        providerId: 'moh',
        amount: '₱150,000/year',
        deadline: 'April 1, 2026',
        level: 'College',
        status: 'Open',
        courses: ['Nursing', 'MedTech', 'Pharmacy', 'Midwifery'],
        location: 'BARMM Residents',
        description: 'Scholarship for students pursuing health-related courses to serve the Bangsamoro people.',
        benefits: ['Tuition Subsidy', 'Uniform Allowance', 'Clinical Internship Support'],
        eligibility: ['Enrolled in Health Course', 'BARMM Resident'],
        requirements: ['Enrollment Form', 'Grades'],
    },
];

export const mockSuccessStories: SuccessStory[] = [
    {
        id: '1',
        name: 'Maria Santos, RN',
        role: 'Staff Nurse',
        school: 'Notre Dame University',
        field: 'Nursing',
        year: '2020-2024',
        program: 'AHME Scholar',
        photo: 'https://placehold.co/400x400?text=Maria',
        story: "Growing up in a farming family in Maguindanao, I never thought I could afford a nursing degree. The AHME scholarship didn't just fund my education—it gave me a community of mentors and fellow scholars who pushed me to excel. Today, I serve at the Cotabato Regional Hospital, giving back to the community that raised me.",
        achievements: ['Passed Nursing Board Exam (Top 10%)', "Dean's Lister (8 semesters)"],
    },
    {
        id: '2',
        name: 'Ahmed Hassan',
        role: 'Software Engineer',
        school: 'Mindanao State University',
        field: 'BS Computer Science',
        year: '2018-2022',
        program: 'BASE Scholar',
        photo: 'https://placehold.co/400x400?text=Ahmed',
        story: "The mentorship program connected me with tech leaders. Now I build tools for my community.",
    },
];
