# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_per_semester', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_start', models.DateTimeField()),
                ('application_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('level', models.CharField(choices=[('shs', 'Senior High School'), ('undergrad', 'Undergraduate'), ('graduate', 'Graduate'), ('vocational', 'Vocational')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-application_deadline'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('field_name', models.CharField(help_text='Field name in profile to validate against', max_length=100)),
                ('operator', models.CharField(default='>=', max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scholarships.scholarshipprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
